### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by mikaelhertzman** [Dodotree/DropzonePHPchunks#6]
First of all - thanks to everyone involved in contributing to these files. I am currently trying to customize them to fit my purposes and at the same time understand them. Below are the parts I find confusing despite pouring a lot of time into the code.

I would be super grateful if I could get some help understanding the following lines.

**Loop through $FILES?:**
https://github.com/Dodotree/DropzonePHPchunks/blob/abf2377650a2595e1acbb6b61de60468a7b69ab9/chunks.php#L24
Isn't this loop only required if we have multiple file inputs in the same form as according to [PHO Uploading multiple files](https://www.php.net/manual/en/features.file-upload.multiple.php)? I am trying to understand if there is any other need to loop through the $FILES array since Dropzone seems Dropzone seems to handle multiple files (regardless of drag and drop or clicking and selecting files) as individual requests.

**$file['filename']:**
https://github.com/Dodotree/DropzonePHPchunks/blob/abf2377650a2595e1acbb6b61de60468a7b69ab9/chunks.php#L35
Is $file['filename'] set by Dropzone or is it a custom variable used in this script? Despite extensive experiments I can't see $file['filename'] ever being populated with a value. [PHP POST method uploads](https://www.php.net/manual/en/features.file-upload.post-method.php) mentions $_FILES['userfile']['name'] but not _filename_ so will this ever not be empty? What I am trying to get at is if there is a reason this row is not just simply `$filename =  $file['name']`; 

**$tmp_file_path:**
https://github.com/Dodotree/DropzonePHPchunks/blob/abf2377650a2595e1acbb6b61de60468a7b69ab9/chunks.php#L42
Why is $tmp_file_path updated here? The only place I can see it being used is in the function `resumableUpload()` which is called three lines before $tmp_file_path is updated. It seems a bit pointless to update a variable after it is already used, but this might have something to do with my first question.

**Comment by Dodotree** [comment]
Hello, Mikael! Since it was a very long time ago, I'm a bit rusty about how it used to work. (I thought that with new mighty browsers and new PHP, it was not really needed any more). I have another version of the same thing at the bottom of this file:

https://github.com/Dodotree/Research/blob/master/protein/src/Protein/CoreBundle/Functions/ApiFunctions.php

Maybe that can help you somehow. If not, let me know what PHP version you are on and what you are trying to achieve.

**Comment by mikaelhertzman** [comment]
Hi @Dodotree,

Thank you for your reply!

I am not sure I understand what Research/Protein is, I have only been looking into the DropzonePHPchunks repository you have made available.

What I am trying to do is create a PHP back-end for Dropzone with chunking enabled. I'm sure that browser might have changed since you published your solution but the back-end should still be roughly the same or am I wrong?

I have searched but haven't found any other good examples on how to get Dropzone with chunkts to work properly. It would mean a lot if you could help me or point me in the right direction.

Thank you again!

**Comment by Dodotree** [comment]
Hello, Mikael! I mean, I can hardly imagine the situation where you would need the file to be uploaded in chunks now. The only reason we used this old code for Protein research was that our internet was slow, and uploading ~2GB files was tricky. At the same time, our client was able to upload and download his files in one gulp without any need for progress bars, etc., because he had better internet. You can just configure your server to accept bigger files, and that should do. 

As to your question, yes, I believe that the filename was set in the form.

**Comment by mikaelhertzman** [comment]
Oh, I see. I thought your repository was just a general example of how to get Dropzone and chunk uploads to work with a PHP backend. (**_Just to be clear_**, I am only referring to https://github.com/Dodotree/DropzonePHPchunks and _not_ https://github.com/Dodotree/Research). Is Protein research some kind of framework or do you mean actual research into proteins? 😄 I have never encountered these terms and I'm only interested in getting my Dropzone implementation to work, not anything else.

I know that in most cases I could use server configuration to increase file limits, but I am currently configuring a host on Google Cloud and they only allow 32MB files to be posted (with very few exceptions) hence why I need to use chunking.

Anyway, I appreciate you taking the time to reply. If I have misunderstood the purpose of your work I apologize and will try to look elsewhere for a solution to my issue. :) Thank you again!

**Comment by Dodotree** [comment]
No problem.  Not sure from which project the plain PHP sample came; we just keep useful snippets. There's a reference in the code from where it came originally. Depending on browsers, form handling, chunks naming, and your server settings original file name might not get through. Since the file is not necessarily in chunks, that might have something to do with naming too. DropZone was a nice plugin, perhaps by now it's even better. The back-end handling can use some improvements for sure. Protein research is just one of our clients. The framework is Symfony. It's another example of the use of DropZone and PHP, if you will. Feel free to explore.

**Comment by mikaelhertzman** [comment]
That is super helpful, thank you! I can't believe I missed the source in the top of the file, I will definitely look into that and the Symfony framework.

Thank you again for taking the time to help me out! Stay safe and happy new year!
